name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint (code)
        run: pnpm lint --fix

      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
